# Andrew Fowlie's academic webpage

# Webpage settings

baseurl = "https://andrewfowlie.github.io/"  # End your URL with a `/` trailing slash.
title = "Andrew Fowlie"
copyright = "&copy; 2018 Andrew Fowlie"
theme = "academic"
enableEmoji = false
footnotereturnlinkcontents = "<sup>^</sup>"
googleAnalytics = "UA-105692395-1"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = [ "HTML", "CSS", "RSS" ]
  section = [ "HTML", "RSS" ]

# BlackFriday Markdown rendering - https://gohugo.io/readfiles/bfconfig/

[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).

[params]

  # Webpage theme

  color_theme = "fowlie"
  font = "classic"

  # Personal details

  name = "Andrew Fowlie"
  role = "Post-doctoral researcher in high-energy physics"
  organizations = [{ name="Monash University", url="https://www.monash.edu/"}]
  gravatar = false  
  avatar = "pMAqUYzR_400x400.jpg"  # Specify an avatar image (in `static/img/` folder)
  email = "Andrew.Fowlie@Monash.Edu"
  address = "Monash University, Office 122, School of Physics and Astronomy, Clayton Campus, Clayton, VIC 3800, Australia"
  twitter = 'fowlimon'
  
  # Google maps
  
  map = 1
  map_api_key = "AIzaSyCAUgGv4Oa4rWScBnFxv0BwYVoFQfo1ML4"
  latitude = "-37.910182" 
  longitude = "145.130746"
  zoom = 17

  # Date format
  
  date_format = "Mon, Jan 2, 2006"

  # LaTeX math rendering

  math = true

  # Code highlights

  highlight = false
  
  # Native social sharing buttons
  
  sharing = true

  # Custom CSS and JS assets

  custom_css = []
  custom_js  = []

  # Publication types

  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter',  # 6
    'Thesis'  # 7
  ]

  # Social/Academic Networking

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:andrew.fowlie@monash.edu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "https://twitter.com/fowlimon"
  
  [[params.social]]
     icon = "stack-exchange"
     icon_pack = "fa"
     link = "https://physics.stackexchange.com/users/23389/innisfree?tab=profile"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/andrewfowlie"

  [[params.social]]
    icon = "arxiv"
    icon_pack = "ai"
    link = "https://arxiv.org/find/hep-ph/1/au:+Fowlie_A/0/1/0/all/0/1"

  [[params.social]]
     icon = "inspire"
     icon_pack = "ai"
     link = "http://inspirehep.net/author/profile/A.Fowlie.1"

# Navigation Links

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 3

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 4
  
[[menu.main]]
  name = "Outreach"
  url = "#outreach"
  weight = 5

[[menu.main]]
  name = "CV"
  url = "#cv"
  weight = 6

[[menu.main]]
  name = "Contact me"
  url = "#contact"
  weight = 7

# Taxonomies

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages

[languages.en]
  languageCode = "en-us"
